server:
  port: 0

spring:
  application:
    name: cars-webapi
  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/cars
    user: postgres
    password: postgres

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG